#!/bin/bash

scriptname=$1

echo "" > ~/Public/jssimplebuild/include.js
echo "" > ~/Public/jssimplebuild/include_underscore.js
echo "" > ~/Public/jssimplebuild/include_jquery.js

cat $scriptname > ~/Public/jssimplebuild/include.js
scriptnumber=""

while test $# -gt 0
do
  case "$1" in
    jquery)
      cp ~/Public/jssimplebuild/jquery.js ~/Public/jssimplebuild/include_jquery.js
      ;;
    underscore)
      cp ~/Public/jssimplebuild/underscore.js ~/Public/jssimplebuild/include_underscore.js
      ;;
    *)
#      if [[ $1 =~ ^[0-6]$ ]]; then
#        cat $scriptname > ~/Public/jssimplebuild/include$1.js
#        scriptnumber=$1
#      fi
      ;;
  esac
  shift
done

#if [[ -z "$scriptnumber" ]]; then
#  cat $scriptname > ~/Public/jssimplebuild/include1.js
#fi

open ~/Public/jssimplebuild/index.html

