#!/bin/bash

scriptname=$1

rm -f ~/Public/jssimplebuild/include.js
echo "" > ~/Public/jssimplebuild/include_underscore.js
echo "" > ~/Public/jssimplebuild/include_jquery.js

ln -s $scriptname ~/Public/jssimplebuild/include.js

while test $# -gt 0
do
  case "$1" in
    jquery)
      cp ~/Public/jssimplebuild/jquery.js ~/Public/jssimplebuild/include_jquery.js
      ;;
    underscore)
      cp ~/Public/jssimplebuild/underscore.js ~/Public/jssimplebuild/include_underscore.js
      ;;
    *)
      echo "Bad Peram"
      ;;
  esac
  shift
done

open -a "Google Chrome" ~/Public/jssimplebuild/index.html

